@startuml
left to right direction

Actor User

rectangle application{
User -- (Connect to the car)
User -- (Choose turning mode)
User -- (Choose speed)
User -- (Turn right/left)
User -- (Disconnect from the car)
}
User -- (Turn on/off the lights)
User -- (Honk)
@enduml